services:
  - type: web
    name: shanti-studio-yoga
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        value: postgresql://postgres.bzvpruczqkwnilwflrgo:-3yWeW3%3FrvG%23_6D@aws-0-us-west-2.pooler.supabase.com:5432/postgres